version: "3.9"
services:

  postgres:
    image: postgres:16.2
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    ports: # TODO remove after local tests
      - 15432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  prefect:
    image: prefecthq/prefect:2.18-python3.12
    restart: always
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    volumes:
      - ./data:/prefect
      - ./flows:/flows
    environment:
      - PREFECT_HOME=/prefect
      - PREFECT_LOCAL_STORAGE_PATH=/flows
      - PREFECT_UI_URL=http://127.0.0.1:4200/api
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/prefect
      - RSS_DB=postgresql://postgres:postgres@postgres:5432/rss
    ports:
      - 4200:4200
    healthcheck:
      test: ["CMD-SHELL", "python3 /flows/health.py"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy

  rssagent:
    image: rssagent:latest
    volumes:
      - ./flows/:/flows
    environment:
      - PREFECT_API_URL=http://prefect:4200/api
      - PREFECT_LOCAL_STORAGE_PATH=/flows
      - RSS_DB=postgresql://postgres:postgres@postgres:5432/rss
    depends_on:
      postgres:
        condition: service_healthy
      prefect:
        condition: service_healthy

  mlagent:
    image: mlagent:latest
    volumes:
      - ./flows/:/flows
      - ./mlflow/:/artifacts
    environment:
      - PREFECT_API_URL=http://prefect:4200/api
      - PREFECT_LOCAL_STORAGE_PATH=/flows
      - RSS_DB=postgresql://postgres:postgres@postgres:5432/rss
    depends_on:
      postgres:
        condition: service_healthy
      prefect:
        condition: service_healthy

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.2
    volumes:
      - ./mlflow/:/artifacts
    environment:
      - MLFLOW_TRACKING_URI=postgresql://postgres:postgres@postgres:5432/mlflow
    command: mlflow server --host 0.0.0.0 --port 8080 --default-artifact-root /artifacts --artifacts-destination /artifacts
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy

# TODO check if actually connects to postgres
# --backend-store-uri ${MLFLOW_DB}
